name: Branch Protection Audit Checker Daily 2

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:     # Allows manual triggering

permissions: {}  # No default GITHUB_TOKEN permissions needed since we're using PAT

jobs:
  check-audit-log:
    runs-on: ubuntu-latest
    steps:
      - name: Check Audit Log for Branch Protection Changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            try {
              console.log('Starting audit log check...');
              console.log('Repository:', context.repo.owner + '/' + context.repo.repo);
              
              // Get the current timestamp and 24 hours ago timestamp
              const now = new Date();
              const yesterday = new Date(now.getTime() - (24 * 60 * 60 * 1000));
              
              // Format dates for the query
              const fromDate = yesterday.toISOString().split('T')[0];
              const toDate = now.toISOString().split('T')[0];
              
              // Query the audit log for protected_branch.update_admin_enforced events
              const response = await github.request('GET /orgs/{org}/audit-log', {
                org: context.repo.owner,
                phrase: `action:protected_branch.update_admin_enforced repo:${context.repo.repo} created:${fromDate}..${toDate}`,
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              });
              
              const events = response.data;
              
              if (events && events.length > 0) {
                console.log('Found branch protection changes in audit log');
                
                // Create a detailed message about the changes
                const changeDetails = events.map(event => {
                  return `• Time: ${new Date(event.created_at).toISOString()}\n` +
                         `  Actor: ${event.actor}\n` +
                         `  Action: ${event.action}\n` +
                         `  Branch: ${event.data.protected_branch_name}`;
                }).join('\n\n');
                
                const notificationText = `🚨 Branch Protection Changes Detected!\n\n` +
                  `Repository: ${context.repo.owner}/${context.repo.repo}\n` +
                  `Time Period: Last 24 hours\n\n` +
                  `Changes Found:\n${changeDetails}`;
                
                // Send to Slack
                await fetch(process.env.SLACK_WEBHOOK_URL, {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json',
                  },
                  body: JSON.stringify({
                    text: "🚨 Branch Protection Changes Alert",
                    blocks: [
                      {
                        type: "section",
                        text: {
                          type: "mrkdwn",
                          text: notificationText
                        }
                      }
                    ]
                  })
                });
              } else {
                console.log('No branch protection changes found in the last 24 hours');
                
                // Send "all clear" message to Slack
                await fetch(process.env.SLACK_WEBHOOK_URL, {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json',
                  },
                  body: JSON.stringify({
                    text: "✅ Branch Protection Status",
                    blocks: [
                      {
                        type: "section",
                        text: {
                          type: "mrkdwn",
                          text: `No branch protection changes detected in the last 24 hours\n` +
                                `Repository: ${context.repo.owner}/${context.repo.repo}`
                        }
                      }
                    ]
                  })
                });
              }
              
            } catch (error) {
              console.error('Error checking audit log:', error);
              console.error('Error details:', {
                status: error.status,
                message: error.message,
                documentation_url: error.documentation_url
              });
              
              // Send error to Slack
              await fetch(process.env.SLACK_WEBHOOK_URL, {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                  text: "⚠️ Error Checking Branch Protection Audit Log",
                  blocks: [
                    {
                      type: "section",
                      text: {
                        type: "mrkdwn",
                        text: `Error checking audit log:\n\`\`\`\n${error.message}\n\`\`\``
                      }
                    }
                  ]
                })
              });
              
              throw error;
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
